/**
 * ============================================================================
 *
 *  SourceMod Library 2
 *
 *  File:          version.sp
 *  Description:   Base 64 algorithm.
 *
 *  Copyright (c) 2022 laper32.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * ============================================================================
 */

#if defined _smlib2_version_included
    #endinput
#endif

#define _smlib2_version_included

// version info
#define SMLIB2_NAME             "SourceMod Library 2"
#define SMLIB2_AUTHOR           "laper32"
#define SMLIB2_DESCRIPTION      "Useful functions for sourcemod."
#define SMLIB2_VERSION          "<Major>.<Minor>.<GitCommit>"
#define SMLIB2_DATE             "<Date>"
#define SMLIB2_LINK             "https://www.laper32.net"
