#if defined _smlib2_included
#endinput
#endif
#define _smlib2_included

#define inline stock
#define extern native

// Must include sourcemod, SDKTools, SDKHooks
// Optional include CStrike, PTaH, DHooks

#include <smlib2/const>
#include <smlib2/engine>
#include <smlib2/math>
#include <smlib2/mem>
#include <smlib2/paramparser>
#include <smlib2/fileparser>
#include <smlib2/tools>
#include <smlib2/utils>
#include <smlib2/text>
#include <smlib2/playermgr>
#include <smlib2/hint>
#include <smlib2/md5>
#include <smlib2/base64>
#include <smlib2/sound>
