name: Build-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Dep install
        run: |
          sudo apt-get update
          sudo apt install gcc-multilib
      - name: Build
        run: |
          bash ./ci/build.sh 1.12
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: |
            ./include/**/*.inc