name: Build-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Dep install
        run: |
          sudo apt-get update
          sudo apt install gcc-multilib
      - name: Build
        run: |
          zip 
          bash ./ci/build.sh 1.12
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Build
      #     path: |
      #       ./include/**/*.inc
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./include/**/*.inc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
