name: Build-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Dep install
        run: |
          sudo apt-get update
          sudo apt install gcc-multilib
      - name: Configure Release tag
        run: |
          git fetch --unshallow
          echo "MAJOR=1" >> $GITHUB_ENV
          echo "MINOR=0" >> $GITHUB_ENV
          echo "COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

          echo ${{ env.DATE }}
      - name: Build
        run: |
          bash ./ci/build.sh 1.12
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.COUNT }}
          files: |
            smlib2.zip